import sqlite3

fourth_grade_words = [
    # Unit 1 我的教室 (My Classroom)
    {"word": "classroom", "translation": "教室", "phonetic": "['klɑ:sru:m]", "definition": "a room where a class is taught", "example": "This is our classroom."},
    {"word": "window", "translation": "窗户", "phonetic": "['windrəʊ]", "definition": "an opening in a wall covered with glass", "example": "Open the window, please."},
    {"word": "blackboard", "translation": "黑板", "phonetic": "['blækbɔ:d]", "definition": "a dark board for writing on with chalk", "example": "Look at the blackboard."},
    {"word": "light", "translation": "灯", "phonetic": "['laɪt]", "definition": "something that produces light", "example": "Turn on the light."},
    {"word": "picture", "translation": "图画;照片", "phonetic": "['pɪktʃə]", "definition": "a representation of something in a drawing", "example": "I like this picture."},
    {"word": "door", "translation": "门", "phonetic": "['dɔ:]", "definition": "an opening in a wall with a movable barrier", "example": "Close the door."},
    {"word": "teacher's desk", "translation": "讲台", "phonetic": "['ti:tʃəz desk]", "definition": "the desk for the teacher", "example": "The books are on the teacher's desk."},
    {"word": "computer", "translation": "电脑", "phonetic": "['kəm'pju:tə]", "definition": "an electronic device for processing data", "example": "I have a computer."},
    {"word": "fan", "translation": "风扇", "phonetic": "['fæn]", "definition": "a device with blades that rotate to create airflow", "example": "Turn on the fan."},
    {"word": "wall", "translation": "墙壁", "phonetic": "['wɔ:l]", "definition": "the side of a room or building", "example": "There is a map on the wall."},
    
    # Unit 2 我的学习用品 (My School Things)
    {"word": "schoolbag", "translation": "书包", "phonetic": "['sku:lbæg]", "definition": "a bag for carrying books and supplies", "example": "I have a new schoolbag."},
    {"word": "maths book", "translation": "数学书", "phonetic": "['mæθs bʊk]", "definition": "a book for learning mathematics", "example": "This is my maths book."},
    {"word": "English book", "translation": "英语书", "phonetic": "['ɪŋɡlɪʃ bʊk]", "definition": "a book for learning English", "example": "Put your English book on the desk."},
    {"word": "candy", "translation": "糖果", "phonetic": "['kændi]", "definition": "a sweet food", "example": "I have some candy."},
    {"word": "notebook", "translation": "笔记本", "phonetic": "['nəʊtbʊk]", "definition": "a book for writing notes", "example": "I need a new notebook."},
    {"word": "toy", "translation": "玩具", "phonetic": "['tɔɪ]", "definition": "something for playing", "example": "I have many toys."},
    {"word": "key", "translation": "钥匙", "phonetic": "['ki:]", "definition": "something for opening locks", "example": "This is my key."},
    {"word": "lost", "translation": "丢失", "phonetic": "['lɒst]", "definition": "unable to find something", "example": "I lost my pencil."},
    {"word": "found", "translation": "找到", "phonetic": "['faʊnd]", "definition": "have found something", "example": "I found a pen."},
    {"word": "knife", "translation": "小刀", "phonetic": "['naɪf]", "definition": "a tool with a sharp blade", "example": "Be careful with the knife."},
    {"word": "isn't", "translation": "不是", "phonetic": "['ɪzənt]", "definition": "short form of is not", "example": "It isn't mine."},
    {"word": "what's", "translation": "是什么", "phonetic": "['wɒts]", "definition": "short form of what is", "example": "What's in your bag?"},
    
    # Unit 3 朋友 (Friends)
    {"word": "friend", "translation": "朋友", "phonetic": "['frend]", "definition": "a person you know well and like", "example": "She is my friend."},
    {"word": "Chinese", "translation": "中国人;中文", "phonetic": "['tʃaɪ'ni:z]", "definition": "a person from China or the language", "example": "He is Chinese."},
    {"word": "name", "translation": "名字", "phonetic": "['neɪm]", "definition": "what someone is called", "example": "My name is Amy."},
    {"word": "student", "translation": "学生", "phonetic": "['stju:dənt]", "definition": "a person who studies at school", "example": "I am a student."},
    {"word": "room", "translation": "房间", "phonetic": "['ru:m]", "definition": "a part of a building", "example": "I have my own room."},
    {"word": "bedroom", "translation": "卧室", "phonetic": "['bedru:m]", "definition": "a room for sleeping", "example": "I have a big bedroom."},
    {"word": "bathroom", "translation": "卫生间", "phonetic": "['bæθru:m]", "definition": "a room for washing", "example": "Where is the bathroom?"},
    {"word": "living room", "translation": "客厅", "phonetic": "['lɪvɪŋ ru:m]", "definition": "a room for family activities", "example": "Watch TV in the living room."},
    {"word": "kitchen", "translation": "厨房", "phonetic": "['kɪtʃɪn]", "definition": "a room for cooking", "example": "My mother is in the kitchen."},
    {"word": "school", "translation": "学校", "phonetic": "['sku:l]", "definition": "a place for learning", "example": "I go to school every day."},
    {"word": "street", "translation": "街道", "phonetic": "['stri:t]", "definition": "a road in a city or town", "example": "I live on this street."},
    {"word": "there", "translation": "那里", "phonetic": "['ðeə]", "definition": "in or at that place", "example": "The school is there."},
    {"word": "home", "translation": "家", "phonetic": "['həʊm]", "definition": "where a family lives", "example": "I am at home."},
    {"word": "classmate", "translation": "同班同学", "phonetic": "['klɑ:smeɪt]", "definition": "a member of the same class", "example": "She is my classmate."},
    {"word": "village", "translation": "乡村", "phonetic": "['vɪlɪdʒ]", "definition": "a small group of houses in the country", "example": "I live in a village."},
    
    # Unit 4 家具和物品 (Furniture and Things)
    {"word": "home", "translation": "家", "phonetic": "['həʊm]", "definition": "where a family lives", "example": "I am at home."},
    {"word": "room", "translation": "房间", "phonetic": "['ru:m]", "definition": "a part of a building", "example": "I have my own room."},
    {"word": "bed", "translation": "床", "phonetic": "['bed]", "definition": "a piece of furniture for sleeping", "example": "I get up from my bed."},
    {"word": "phone", "translation": "电话", "phonetic": "['fəʊn]", "definition": "a device for talking to someone far away", "example": "Call me on my phone."},
    {"word": "table", "translation": "桌子", "phonetic": "['teɪbl]", "definition": "a piece of furniture with a flat top", "example": "The books are on the table."},
    {"word": "sofa", "translation": "沙发", "phonetic": "['səʊfə]", "definition": "a comfortable seat for two or more people", "example": "I sit on the sofa."},
    {"word": "shelf", "translation": "书架", "phonetic": "['ʃelf]", "definition": "a board for holding books", "example": "Put the book on the shelf."},
    {"word": "fridge", "translation": "冰箱", "phonetic": "['frɪdʒ]", "definition": "a device for keeping food cold", "example": "The milk is in the fridge."},
    {"word": "armchair", "translation": "扶手椅", "phonetic": "['ɑ:mtʃeə]", "definition": "a comfortable chair with arms", "example": "I sit in the armchair."},
    {"word": "end table", "translation": "茶几", "phonetic": "['end teɪbl]", "definition": "a small table next to a sofa", "example": "The lamp is on the end table."},
    {"word": "TV", "translation": "电视", "phonetic": "['ti: 'vi:]", "definition": "a device for watching programs", "example": "I watch TV after dinner."},
    {"word": "mirror", "translation": "镜子", "phonetic": "['mɪrə]", "definition": "a glass surface that reflects images", "example": "Look in the mirror."},
    {"word": "closet", "translation": "衣柜", "phonetic": "['klɒzɪt]", "definition": "a cabinet for storing clothes", "example": "My clothes are in the closet."},
    {"word": "curtain", "translation": "窗帘", "phonetic": "['kɜ:tən]", "definition": "cloth covering a window", "example": "Open the curtains."},
    {"word": "trash bin", "translation": "垃圾桶", "phonetic": "['træʃ bɪn]", "definition": "a container for waste", "example": "Put the paper in the trash bin."},
    
    # Unit 5 食物 (Food)
    {"word": "bread", "translation": "面包", "phonetic": "['bred]", "definition": "food made from flour and baked", "example": "I eat bread for breakfast."},
    {"word": "juice", "translation": "果汁", "phonetic": "['dʒu:s]", "definition": "drink made from fruit", "example": "I like orange juice."},
    {"word": "egg", "translation": "鸡蛋", "phonetic": "['eg]", "definition": "food from chickens", "example": "I have an egg for breakfast."},
    {"word": "milk", "translation": "牛奶", "phonetic": "['mɪlk]", "definition": "white drink from cows", "example": "I drink milk every day."},
    {"word": "rice", "translation": "米饭", "phonetic": "['raɪs]", "definition": "food from Asia made from grains", "example": "I eat rice for lunch."},
    {"word": "noodles", "translation": "面条", "phonetic": "['nu:dlz]", "definition": "long thin food made from flour", "example": "I like noodles."},
    {"word": "fish", "translation": "鱼", "phonetic": "['fɪʃ]", "definition": "food from water that can swim", "example": "I eat fish for dinner."},
    {"word": "beef", "translation": "牛肉", "phonetic": "['bi:f]", "definition": "meat from cows", "example": "I like beef."},
    {"word": "vegetable", "translation": "蔬菜", "phonetic": "['vedʒtəbl]", "definition": "plant food", "example": "Eat your vegetables."},
    {"word": "fruit", "translation": "水果", "phonetic": "['fru:t]", "definition": "sweet food from plants", "example": "I like fruit."},
    {"word": "chicken", "translation": "鸡肉", "phonetic": "['tʃɪkɪn]", "definition": "meat from chickens", "example": "I like chicken."},
    {"word": "hungry", "translation": "饥饿的", "phonetic": "['hʌŋɡri]", "definition": "feeling a need for food", "example": "I'm hungry."},
    {"word": "thirsty", "translation": "渴的", "phonetic": "['θɜ:sti]", "definition": "feeling a need for drink", "example": "I'm thirsty."},
    {"word": "breakfast", "translation": "早餐", "phonetic": "['brekfəst]", "definition": "the first meal of the day", "example": "I have breakfast at 7 o'clock."},
    {"word": "lunch", "translation": "午餐", "phonetic": "['lʌntʃ]", "definition": "the meal in the middle of the day", "example": "I have lunch at school."},
    {"word": "dinner", "translation": "晚餐", "phonetic": "['dɪnə]", "definition": "the last meal of the day", "example": "I have dinner with my family."},
    {"word": "delicious", "translation": "美味的", "phonetic": "['dɪ'lɪʃəs]", "definition": "tasting very good", "example": "The food is delicious."},
    {"word": "sandwich", "translation": "三明治", "phonetic": "['sændwɪtʃ]", "definition": "food between two slices of bread", "example": "I like sandwiches."},
    {"word": "salad", "translation": "沙拉", "phonetic": "['sæləd]", "definition": "a dish of raw vegetables", "example": "I eat salad for lunch."},
    {"word": "soup", "translation": "汤", "phonetic": "['su:p]", "definition": "liquid food", "example": "I drink soup."},
    {"word": "dumpling", "translation": "饺子", "phonetic": "['dʌmplɪŋ]", "definition": "food with filling wrapped in dough", "example": "I like dumplings."},
    {"word": "pizza", "translation": "披萨", "phonetic": "['pi:tsə]", "definition": "flat bread with cheese and toppings", "example": "I like pizza."},
    {"word": "hot dog", "translation": "热狗", "phonetic": "['hɒt dɒg]", "definition": "bread with a sausage inside", "example": "I eat a hot dog."},
    {"word": "hamburger", "translation": "汉堡包", "phonetic": "['hæmbɜ:gə]", "definition": "bread with meat and vegetables", "example": "I like hamburgers."},
    {"word": "coffee", "translation": "咖啡", "phonetic": "['kɒfi]", "definition": "a hot dark drink", "example": "My father drinks coffee."},
    {"word": "tea", "translation": "茶", "phonetic": "['ti:]", "definition": "a hot drink made from leaves", "example": "I drink tea."},
    {"word": "water", "translation": "水", "phonetic": "['wɔ:tə]", "definition": "a clear drink", "example": "I drink water."},
    
    # Unit 6 家庭成员 (Family Members)
    {"word": "parents", "translation": "父母", "phonetic": "['peərənts]", "definition": "mother and father", "example": "My parents are nice."},
    {"word": "uncle", "translation": "叔叔;舅舅", "phonetic": "['ʌŋkl]", "definition": "father's or mother's brother", "example": "My uncle is tall."},
    {"word": "aunt", "translation": "阿姨;姑妈", "phonetic": "['ɑ:nt]", "definition": "father's or mother's sister", "example": "My aunt is kind."},
    {"word": "baby", "translation": "婴儿", "phonetic": "['beɪbi]", "definition": "a very young child", "example": "The baby is cute."},
    {"word": "doctor", "translation": "医生", "phonetic": "['dɒktə]", "definition": "a person who helps sick people", "example": "My mother is a doctor."},
    {"word": "cook", "translation": "厨师", "phonetic": "['kʊk]", "definition": "a person who cooks food", "example": "My father is a cook."},
    {"word": "driver", "translation": "司机", "phonetic": "['draɪvə]", "definition": "a person who drives vehicles", "example": "My uncle is a driver."},
    {"word": "farmer", "translation": "农民", "phonetic": "['fɑ:mə]", "definition": "a person who works on a farm", "example": "My grandfather is a farmer."},
    {"word": "nurse", "translation": "护士", "phonetic": "['nɜ:s]", "definition": "a person who helps doctors", "example": "My aunt is a nurse."},
    {"word": "sister", "translation": "姐妹", "phonetic": "['sɪstə]", "definition": "a girl with the same parents", "example": "I have a sister."},
    {"word": "brother", "translation": "兄弟", "phonetic": "['brʌðə]", "definition": "a boy with the same parents", "example": "I have a brother."},
    {"word": "grandmother", "translation": "外祖母;祖母", "phonetic": "['ɡrændmʌðə]", "definition": "mother of one's parent", "example": "My grandmother is kind."},
    {"word": "grandfather", "translation": "外祖父;祖父", "phonetic": "['ɡrændfɑ:ðə]", "definition": "father of one's parent", "example": "My grandfather is old."},
    {"word": "grandpa", "translation": "爷爷;外公", "phonetic": "['ɡrænpɑ:]", "definition": "grandfather (informal)", "example": "I love my grandpa."},
    {"word": "grandma", "translation": "奶奶;外婆", "phonetic": "['ɡrænmɑ:]", "definition": "grandmother (informal)", "example": "I love my grandma."},
    {"word": "cousin", "translation": "堂(表)兄弟姐妹", "phonetic": "['kʌzən]", "definition": "child of one's aunt or uncle", "example": "My cousin is my friend."},
    {"word": "family", "translation": "家庭", "phonetic": "['fæmɪli]", "definition": "a group of related people", "example": "I have a big family."},
    
    # 常用形容词 (Adjectives)
    {"word": "tall", "translation": "高的", "phonetic": "['tɔ:l]", "definition": "of great height", "example": "He is tall."},
    {"word": "short", "translation": "矮的;短的", "phonetic": "['ʃɔ:t]", "definition": "of small height or length", "example": "I am short."},
    {"word": "strong", "translation": "强壮的", "phonetic": "['strɒŋ]", "definition": "having great power", "example": "My father is strong."},
    {"word": "quiet", "translation": "安静的", "phonetic": "['kwaɪət]", "definition": "with little noise", "example": "Be quiet in the library."},
    {"word": "friendly", "translation": "友好的", "phonetic": "['frendli]", "definition": "kind and nice to others", "example": "She is friendly."},
    {"word": "helpful", "translation": "有用的;乐于助人的", "phonetic": "['helpfʊl]", "definition": "able to help", "example": "She is helpful."},
    {"word": "old", "translation": "老的;旧的", "phonetic": "['əʊld]", "definition": "not young or new", "example": "My grandfather is old."},
    {"word": "young", "translation": "年轻的", "phonetic": "['jʌŋ]", "definition": "not old", "example": "My mother is young."},
    {"word": "big", "translation": "大的", "phonetic": "['bɪɡ]", "definition": "of considerable size", "example": "I have a big bedroom."},
    {"word": "small", "translation": "小的", "phonetic": "['smɔ:l]", "definition": "of limited size", "example": "I have a small room."},
    {"word": "long", "translation": "长的", "phonetic": "['lɒŋ]", "definition": "of great length", "example": "I have long hair."},
    {"word": "thin", "translation": "瘦的", "phonetic": "['θɪn]", "definition": "not fat", "example": "She is thin."},
    {"word": "fat", "translation": "胖的", "phonetic": "['fæt]", "definition": "having much flesh", "example": "The cat is fat."},
    {"word": "happy", "translation": "高兴的", "phonetic": "['hæpi]", "definition": "feeling or showing pleasure", "example": "I am happy today."},
    {"word": "sad", "translation": "悲伤的", "phonetic": "['sæd]", "definition": "feeling sorrow", "example": "She looks sad."},
    {"word": "cute", "translation": "可爱的", "phonetic": "['kju:t]", "definition": "attractive and endearing", "example": "The baby is cute."},
    {"word": "active", "translation": "活跃的", "phonetic": "['æktɪv]", "definition": "energetic and lively", "example": "He is very active."},
    {"word": "smart", "translation": "聪明的", "phonetic": "['smɑ:t]", "definition": "intelligent", "example": "She is very smart."},
    {"word": "funny", "translation": "有趣的;滑稽的", "phonetic": "['fʌni]", "definition": "humorous", "example": "He is funny."},
    
    # 常用动词 (Verbs)
    {"word": "eat", "translation": "吃", "phonetic": "['i:t]", "definition": "put food in your mouth and swallow", "example": "I eat breakfast at home."},
    {"word": "drink", "translation": "喝", "phonetic": "['drɪŋk]", "definition": "take liquid into your mouth", "example": "I drink water every day."},
    {"word": "sleep", "translation": "睡觉", "phonetic": "['sli:p]", "definition": "rest with eyes closed", "example": "I go to sleep at 9 o'clock."},
    {"word": "wake up", "translation": "醒来", "phonetic": "['weɪk ʌp]", "definition": "stop sleeping", "example": "I wake up at 6 o'clock."},
    {"word": "play", "translation": "玩;打(球)", "phonetic": "['pleɪ]", "definition": "have fun or take part in sports", "example": "I play football on Saturdays."},
    {"word": "read", "translation": "读", "phonetic": "['ri:d]", "definition": "look at and understand words", "example": "I like reading books."},
    {"word": "write", "translation": "写", "phonetic": "['raɪt]", "definition": "make letters on paper", "example": "I write with a pencil."},
    {"word": "draw", "translation": "画", "phonetic": "['drɔ:]", "definition": "make pictures with a pen", "example": "I like to draw."},
    {"word": "watch", "translation": "看", "phonetic": "['wɒtʃ]", "definition": "look at something for a time", "example": "I watch TV after dinner."},
    {"word": "cook", "translation": "烹饪", "phonetic": "['kʊk]", "definition": "prepare food by heating", "example": "My mother cooks dinner."},
    {"word": "clean", "translation": "打扫", "phonetic": "['kli:n]", "definition": "make something clean", "example": "I clean my room."},
    {"word": "live", "translation": "居住", "phonetic": "['lɪv]", "definition": "have one's home in a place", "example": "I live in Beijing."},
    {"word": "study", "translation": "学习", "phonetic": "['stʌdi]", "definition": "spend time learning", "example": "I study English every day."},
    {"word": "swim", "translation": "游泳", "phonetic": "['swɪm]", "definition": "move through water", "example": "I can swim."},
    {"word": "run", "translation": "跑", "phonetic": "['rʌn]", "definition": "move fast on foot", "example": "I run to school."},
    {"word": "walk", "translation": "走;步行", "phonetic": "['wɔ:k]", "definition": "move on foot", "example": "I walk to school."},
    {"word": "sing", "translation": "唱", "phonetic": "['sɪŋ]", "definition": "make musical sounds with voice", "example": "I like to sing."},
    {"word": "dance", "translation": "跳舞", "phonetic": "['dɑ:ns]", "definition": "move to music", "example": "I like to dance."},
    {"word": "fly", "translation": "放飞;飞", "phonetic": "['flaɪ]", "definition": "move through the air", "example": "I fly a kite in the park."},
    {"word": "make", "translation": "制作", "phonetic": "['meɪk]", "definition": "create or produce", "example": "I make a cake."},
    {"word": "have", "translation": "有", "phonetic": "['hæv]", "definition": "own something", "example": "I have a new book."},
    {"word": "go", "translation": "去", "phonetic": "['gəʊ]", "definition": "move to a place", "example": "I go to school by bus."},
    {"word": "come", "translation": "来", "phonetic": "['kʌm]", "definition": "move to or towards", "example": "Come here, please."},
    {"word": "know", "translation": "知道", "phonetic": "['nəʊ]", "definition": "have knowledge of something", "example": "I know the answer."},
    {"word": "think", "translation": "认为;想", "phonetic": "['θɪŋk]", "definition": "use one's mind", "example": "I think so."},
    {"word": "love", "translation": "爱", "phonetic": "['lʌv]", "definition": "feel deep affection", "example": "I love my family."},
    {"word": "like", "translation": "喜欢", "phonetic": "['laɪk]", "definition": "enjoy something", "example": "I like apples."},
    
    # 常用介词和方位词 (Prepositions and Direction Words)
    {"word": "in", "translation": "在……里面", "phonetic": "['ɪn]", "definition": "inside something", "example": "The cat is in the box."},
    {"word": "on", "translation": "在……上面", "phonetic": "['ɒn]", "definition": "on top of something", "example": "The book is on the table."},
    {"word": "under", "translation": "在……下面", "phonetic": "['ʌndə]", "definition": "below something", "example": "The ball is under the chair."},
    {"word": "near", "translation": "在……附近", "phonetic": "['nɪə]", "definition": "close to something", "example": "The school is near my home."},
    {"word": "behind", "translation": "在……后面", "phonetic": "['bɪ'haɪnd]", "definition": "at the back of something", "example": "The cat is behind the door."},
    {"word": "in front of", "translation": "在……前面", "phonetic": "['ɪn frʌnt ɒv]", "definition": "before something", "example": "I stand in front of the blackboard."},
    {"word": "between", "translation": "在……中间", "phonetic": "['bɪ'twi:n]", "definition": "in the middle of two things", "example": "The ball is between the two chairs."},
    {"word": "next to", "translation": "在……旁边", "phonetic": "['nekst tu:]", "definition": "beside something", "example": "I sit next to my friend."},
    {"word": "above", "translation": "在……上方", "phonetic": "['ə'bʌv]", "definition": "higher than something", "example": "The plane is above the clouds."},
    {"word": "over", "translation": "在……上方", "phonetic": "['əʊvə]", "definition": "across or on top of something", "example": "The bridge is over the river."},
    
    # 数字 (Numbers)
    {"word": "one", "translation": "一", "phonetic": "['wʌn]", "definition": "the number 1", "example": "I have one apple."},
    {"word": "two", "translation": "二", "phonetic": "['tu:]", "definition": "the number 2", "example": "I have two books."},
    {"word": "three", "translation": "三", "phonetic": "['θri:]", "definition": "the number 3", "example": "I have three pencils."},
    {"word": "four", "translation": "四", "phonetic": "['fɔ:]", "definition": "the number 4", "example": "I am four years old."},
    {"word": "five", "translation": "五", "phonetic": "['faɪv]", "definition": "the number 5", "example": "I have five fingers."},
    {"word": "six", "translation": "六", "phonetic": "['sɪks]", "definition": "the number 6", "example": "I wake up at six."},
    {"word": "seven", "translation": "七", "phonetic": "['sevən]", "definition": "the number 7", "example": "I have seven colors."},
    {"word": "eight", "translation": "八", "phonetic": "['eɪt]", "definition": "the number 8", "example": "There are eight books."},
    {"word": "nine", "translation": "九", "phonetic": "['naɪn]", "definition": "the number 9", "example": "My sister is nine."},
    {"word": "ten", "translation": "十", "phonetic": "['ten]", "definition": "the number 10", "example": "I have ten fingers."},
    {"word": "eleven", "translation": "十一", "phonetic": "['ɪ'levən]", "definition": "the number 11", "example": "I am eleven years old."},
    {"word": "twelve", "translation": "十二", "phonetic": "['twelv]", "definition": "the number 12", "example": "I have twelve pencils."},
    {"word": "thirteen", "translation": "十三", "phonetic": "['θɜ:'ti:n]", "definition": "the number 13", "example": "There are thirteen students."},
    {"word": "fourteen", "translation": "十四", "phonetic": "['fɔ:'ti:n]", "definition": "the number 14", "example": "I wake up at fourteen past seven."},
    {"word": "fifteen", "translation": "十五", "phonetic": "['fɪf'ti:n]", "definition": "the number 15", "example": "It is fifteen degrees today."},
    {"word": "sixteen", "translation": "十六", "phonetic": "['sɪks'ti:n]", "definition": "the number 16", "example": "I am sixteen years old."},
    {"word": "seventeen", "translation": "十七", "phonetic": "['sevən'ti:n]", "definition": "the number 17", "example": "The bus comes at seventeen past eight."},
    {"word": "eighteen", "translation": "十八", "phonetic": "['eɪ'ti:n]", "definition": "the number 18", "example": "I have eighteen books."},
    {"word": "nineteen", "translation": "十九", "phonetic": "['naɪn'ti:n]", "definition": "the number 19", "example": "There are nineteen apples."},
    {"word": "twenty", "translation": "二十", "phonetic": "['twenti]", "definition": "the number 20", "example": "I have twenty classmates."},
    
    # 颜色 (Colors)
    {"word": "red", "translation": "红色", "phonetic": "['red]", "definition": "the color of blood", "example": "I have a red pen."},
    {"word": "blue", "translation": "蓝色", "phonetic": "['blu:]", "definition": "the color of the sky", "example": "The sky is blue."},
    {"word": "yellow", "translation": "黄色", "phonetic": "['jeləʊ]", "definition": "the color of the sun", "example": "I have a yellow bag."},
    {"word": "green", "translation": "绿色", "phonetic": "['gri:n]", "definition": "the color of grass", "example": "The grass is green."},
    {"word": "orange", "translation": "橙色", "phonetic": "['ɒrɪndʒ]", "definition": "the color of oranges", "example": "I have an orange."},
    {"word": "purple", "translation": "紫色", "phonetic": "['pɜ:pl]", "definition": "a color between red and blue", "example": "I have a purple pencil."},
    {"word": "pink", "translation": "粉色", "phonetic": "['pɪŋk]", "definition": "light red color", "example": "I like pink flowers."},
    {"word": "black", "translation": "黑色", "phonetic": "['blæk]", "definition": "the darkest color", "example": "I have a black cat."},
    {"word": "white", "translation": "白色", "phonetic": "['waɪt]", "definition": "the lightest color", "example": "The paper is white."},
    {"word": "brown", "translation": "棕色", "phonetic": "['braʊn]", "definition": "the color of chocolate", "example": "I have a brown bag."},
    {"word": "gray", "translation": "灰色", "phonetic": "['ɡreɪ]", "definition": "a color between black and white", "example": "The elephant is gray."},
    
    # 动物 (Animals)
    {"word": "cat", "translation": "猫", "phonetic": "['kæt]", "definition": "a small animal that meows", "example": "I have a pet cat."},
    {"word": "dog", "translation": "狗", "phonetic": "['dɒg]", "definition": "a small animal that barks", "example": "I have a pet dog."},
    {"word": "bird", "translation": "鸟", "phonetic": "['bɜ:d]", "definition": "an animal that can fly", "example": "The bird is singing."},
    {"word": "rabbit", "translation": "兔子", "phonetic": "['ræbɪt]", "definition": "a small animal with long ears", "example": "The rabbit is cute."},
    {"word": "mouse", "translation": "老鼠", "phonetic": "['maʊs]", "definition": "a small animal", "example": "The mouse is in the hole."},
    {"word": "elephant", "translation": "大象", "phonetic": "['elifənt]", "definition": "a very large animal with a trunk", "example": "The elephant has a long nose."},
    {"word": "tiger", "translation": "老虎", "phonetic": "['taɪɡə]", "definition": "a large wild cat", "example": "The tiger is strong."},
    {"word": "lion", "translation": "狮子", "phonetic": "['laɪən]", "definition": "a large wild cat", "example": "The lion is the king of animals."},
    {"word": "monkey", "translation": "猴子", "phonetic": "['mʌŋki]", "definition": "an animal that climbs trees", "example": "The monkey is funny."},
    {"word": "panda", "translation": "熊猫", "phonetic": "['pændə]", "definition": "a black and white bear", "example": "Pandas are cute."},
    {"word": "zebra", "translation": "斑马", "phonetic": "['zi:brə]", "definition": "an animal with stripes", "example": "The zebra has black and white stripes."},
    {"word": "giraffe", "translation": "长颈鹿", "phonetic": "['dʒə'rɑ:f]", "definition": "a tall animal with a long neck", "example": "The giraffe has a long neck."},
    {"word": "duck", "translation": "鸭子", "phonetic": "['dʌk]", "definition": "a water bird", "example": "The duck is swimming."},
    {"word": "chicken", "translation": "鸡", "phonetic": "['tʃɪkɪn]", "definition": "a farm bird", "example": "The chicken lays eggs."},
    {"word": "pig", "translation": "猪", "phonetic": "['pɪɡ]", "definition": "a fat farm animal", "example": "The pig is eating."},
    {"word": "cow", "translation": "奶牛", "phonetic": "['kaʊ]", "definition": "a farm animal that gives milk", "example": "The cow gives milk."},
    {"word": "sheep", "translation": "绵羊", "phonetic": "['ʃi:p]", "definition": "a farm animal with wool", "example": "The sheep has wool."},
    {"word": "horse", "translation": "马", "phonetic": "['hɔ:s]", "definition": "a large animal that can run fast", "example": "The horse is running."},
    {"word": "snake", "translation": "蛇", "phonetic": "['sneɪk]", "definition": "a long animal without legs", "example": "The snake is crawling."},
    {"word": "frog", "translation": "青蛙", "phonetic": "['frɒɡ]", "definition": "a small animal that lives in water", "example": "The frog can jump."},
    
    # 人体部位 (Body Parts)
    {"word": "head", "translation": "头", "phonetic": "['hed]", "definition": "the part of the body on top of the neck", "example": "I have a headache."},
    {"word": "face", "translation": "脸", "phonetic": "['feɪs]", "definition": "the front of the head", "example": "Wash your face."},
    {"word": "eye", "translation": "眼睛", "phonetic": "['aɪ]", "definition": "the part of the body for seeing", "example": "I have two eyes."},
    {"word": "nose", "translation": "鼻子", "phonetic": "['nəʊz]", "definition": "the part of the face for smelling", "example": "My nose is big."},
    {"word": "mouth", "translation": "嘴巴", "phonetic": "['maʊθ]", "definition": "the part of the face for eating", "example": "Open your mouth."},
    {"word": "ear", "translation": "耳朵", "phonetic": "['ɪə]", "definition": "the part of the body for hearing", "example": "I have two ears."},
    {"word": "hair", "translation": "头发", "phonetic": "['heə]", "definition": "threads that grow on the head", "example": "I have long hair."},
    {"word": "arm", "translation": "手臂", "phonetic": "['ɑ:m]", "definition": "the part of the body between shoulder and hand", "example": "I have two arms."},
    {"word": "hand", "translation": "手", "phonetic": "['hænd]", "definition": "the part of the arm at the end", "example": "Raise your hand."},
    {"word": "leg", "translation": "腿", "phonetic": "['leɡ]", "definition": "the part of the body used for walking", "example": "I have two legs."},
    {"word": "foot", "translation": "脚", "phonetic": "['fʊt]", "definition": "the part of the leg at the bottom", "example": "I have two feet."},
    {"word": "body", "translation": "身体", "phonetic": "['bɒdi]", "definition": "the whole physical form", "example": "Wash your body."},
    {"word": "stomach", "translation": "胃;肚子", "phonetic": "['stʌmək]", "definition": "the part of the body for digesting food", "example": "I have a stomachache."},
    {"word": "back", "translation": "背", "phonetic": "['bæk]", "definition": "the rear part of the body", "example": "My back hurts."},
    
    # 时间表达 (Time Expressions)
    {"word": "o'clock", "translation": "……点", "phonetic": "['ə'klɒk]", "definition": "used to say what hour it is", "example": "It is seven o'clock."},
    {"word": "time", "translation": "时间", "phonetic": "['taɪm]", "definition": "the continued sequence of existence", "example": "What time is it?"},
    {"word": "morning", "translation": "早晨;上午", "phonetic": "['mɔ:nɪŋ]", "definition": "the early part of the day", "example": "I do exercise in the morning."},
    {"word": "afternoon", "translation": "下午", "phonetic": "['ɑ:ftə'nu:n]", "definition": "the time between noon and evening", "example": "I have class in the afternoon."},
    {"word": "evening", "translation": "傍晚;晚上", "phonetic": "['i:vnɪŋ]", "definition": "the time between afternoon and night", "example": "I do homework in the evening."},
    {"word": "night", "translation": "夜间", "phonetic": "['naɪt]", "definition": "the time of darkness", "example": "I go to bed at night."},
    {"word": "today", "translation": "今天", "phonetic": "['tə'deɪ]", "definition": "this day", "example": "Today is Monday."},
    {"word": "tomorrow", "translation": "明天", "phonetic": "['tə'mɒrəʊ]", "definition": "the day after today", "example": "I will go to school tomorrow."},
    {"word": "yesterday", "translation": "昨天", "phonetic": "['jestədeɪ]", "definition": "the day before today", "example": "I played games yesterday."},
    {"word": "week", "translation": "周;星期", "phonetic": "['wi:k]", "definition": "a period of seven days", "example": "I go to school every week."},
    {"word": "weekend", "translation": "周末", "phonetic": "['wi:k'end]", "definition": "Saturday and Sunday", "example": "I play on the weekend."},
    {"word": "Monday", "translation": "星期一", "phonetic": "['mʌndeɪ]", "definition": "the first day of the week", "example": "I have PE on Monday."},
    {"word": "Tuesday", "translation": "星期二", "phonetic": "['tju:zdeɪ]", "definition": "the second day of the week", "example": "I have art on Tuesday."},
    {"word": "Wednesday", "translation": "星期三", "phonetic": "['wenzdeɪ]", "definition": "the third day of the week", "example": "I have Chinese on Wednesday."},
    {"word": "Thursday", "translation": "星期四", "phonetic": "['θɜ:zdeɪ]", "definition": "the fourth day of the week", "example": "I have math on Thursday."},
    {"word": "Friday", "translation": "星期五", "phonetic": "['fraɪdeɪ]", "definition": "the fifth day of the week", "example": "I have English on Friday."},
    {"word": "Saturday", "translation": "星期六", "phonetic": "['sætədeɪ]", "definition": "the sixth day of the week", "example": "I play sports on Saturday."},
    {"word": "Sunday", "translation": "星期日", "phonetic": "['sʌndeɪ]", "definition": "the seventh day of the week", "example": "I stay at home on Sunday."},
    
    # 衣服 (Clothes)
    {"word": "shirt", "translation": "衬衫", "phonetic": "['ʃɜ:t]", "definition": "a piece of clothing for the upper body", "example": "I have a blue shirt."},
    {"word": "T-shirt", "translation": "T恤衫", "phonetic": "['ti: ʃɜ:t]", "definition": "a casual shirt without a collar", "example": "I wear a T-shirt."},
    {"word": "skirt", "translation": "裙子", "phonetic": "['skɜ:t]", "definition": "a piece of clothing for women", "example": "My mother has a red skirt."},
    {"word": "dress", "translation": "连衣裙", "phonetic": "['dres]", "definition": "a piece of clothing for women", "example": "She is wearing a dress."},
    {"word": "jeans", "translation": "牛仔裤", "phonetic": "['dʒi:nz]", "definition": "casual trousers", "example": "I have blue jeans."},
    {"word": "pants", "translation": "裤子", "phonetic": "['pænts]", "definition": "trousers", "example": "I need new pants."},
    {"word": "shoes", "translation": "鞋子", "phonetic": "['ʃu:z]", "definition": "footwear", "example": "I have new shoes."},
    {"word": "socks", "translation": "袜子", "phonetic": "['sɒks]", "definition": "clothing for the feet", "example": "I have white socks."},
    {"word": "jacket", "translation": "夹克衫", "phonetic": "['dʒækɪt]", "definition": "a short coat", "example": "I have a warm jacket."},
    {"word": "coat", "translation": "外套;大衣", "phonetic": "['kəʊt]", "definition": "outer clothing", "example": "Put on your coat."},
    {"word": "scarf", "translation": "围巾", "phonetic": "['skɑ:f]", "definition": "a piece of cloth for the neck", "example": "I have a red scarf."},
    {"word": "gloves", "translation": "手套", "phonetic": "['glʌvz]", "definition": "coverings for the hands", "example": "I need new gloves."},
    {"word": "umbrella", "translation": "雨伞", "phonetic": "['ʌm'brelə]", "definition": "a device for keeping dry in rain", "example": "Take an umbrella."},
    {"word": "sunglasses", "translation": "太阳镜", "phonetic": "['sʌnɡlɑ:sɪz]", "definition": "glasses for protecting from the sun", "example": "I have cool sunglasses."},
    
    # 交通工具 (Transportation)
    {"word": "bus", "translation": "公共汽车", "phonetic": "['bʌs]", "definition": "a large vehicle for many passengers", "example": "I go to school by bus."},
    {"word": "car", "translation": "小汽车", "phonetic": "['kɑ:]", "definition": "a vehicle for a few passengers", "example": "My father has a car."},
    {"word": "taxi", "translation": "出租车", "phonetic": "['tæksi]", "definition": "a car that you pay to use", "example": "I take a taxi."},
    {"word": "train", "translation": "火车", "phonetic": "['treɪn]", "definition": "a vehicle that runs on rails", "example": "I go to Beijing by train."},
    {"word": "plane", "translation": "飞机", "phonetic": "['pleɪn]", "definition": "a vehicle that flies in the air", "example": "I fly to Shanghai by plane."},
    {"word": "ship", "translation": "轮船", "phonetic": "['ʃɪp]", "definition": "a large boat", "example": "We go to the island by ship."},
    {"word": "bike", "translation": "自行车", "phonetic": "['baɪk]", "definition": "a vehicle with two wheels", "example": "I ride a bike to school."},
    {"word": "motorbike", "translation": "摩托车", "phonetic": "['məʊtəbaɪk]", "definition": "a two-wheeled vehicle with an engine", "example": "My uncle has a motorbike."},
    {"word": "subway", "translation": "地铁", "phonetic": "['sʌbweɪ]", "definition": "an underground railway", "example": "I take the subway to work."},
    {"word": "on foot", "translation": "步行", "phonetic": "['ɒn fʊt]", "definition": "walking", "example": "I go to school on foot."},
    
    # 地点 (Places)
    {"word": "park", "translation": "公园", "phonetic": "['pɑ:k]", "definition": "a public garden for recreation", "example": "I play in the park."},
    {"word": "zoo", "translation": "动物园", "phonetic": "['zu:]", "definition": "a place where animals are kept", "example": "I see animals at the zoo."},
    {"word": "library", "translation": "图书馆", "phonetic": "['laɪbrəri]", "definition": "a place where books are kept", "example": "I read books in the library."},
    {"word": "hospital", "translation": "医院", "phonetic": "['hɒspɪtl]", "definition": "a place where sick people are treated", "example": "My mother works in a hospital."},
    {"word": "cinema", "translation": "电影院", "phonetic": "['sɪnɪmə]", "definition": "a place where films are shown", "example": "I watch movies at the cinema."},
    {"word": "theatre", "translation": "剧院", "phonetic": "['θɪətə]", "definition": "a place where plays are performed", "example": "I see a play at the theatre."},
    {"word": "restaurant", "translation": "餐馆", "phonetic": "['restrɒnt]", "definition": "a place where people eat", "example": "We eat at a restaurant."},
    {"word": "hotel", "translation": "旅馆", "phonetic": "['həʊ'tel]", "definition": "a place where people stay when traveling", "example": "We stay at a hotel."},
    {"word": "supermarket", "translation": "超市", "phonetic": "['sju:pəmɑ:kɪt]", "definition": "a large store", "example": "My mother shops at the supermarket."},
    {"word": "post office", "translation": "邮局", "phonetic": "['pəʊst ɒfɪs]", "definition": "a place where mail is handled", "example": "I send a letter at the post office."},
    {"word": "bank", "translation": "银行", "phonetic": "['bæŋk]", "definition": "a place for keeping money", "example": "My father goes to the bank."},
    {"word": "school", "translation": "学校", "phonetic": "['sku:l]", "definition": "a place for learning", "example": "I go to school every day."},
    {"word": "garden", "translation": "花园", "phonetic": "['ɡɑ:dn]", "definition": "a place where plants are grown", "example": "My grandmother has a garden."},
    {"word": "farm", "translation": "农场", "phonetic": "['fɑ:m]", "definition": "a place for growing food or keeping animals", "example": "We visit a farm."},
    {"word": "playground", "translation": "操场", "phonetic": "['pleɪgraʊnd]", "definition": "a place for playing", "example": "I play on the playground."},
    {"word": "gym", "translation": "体育馆", "phonetic": "['dʒɪm]", "definition": "a place for exercise", "example": "We have PE in the gym."},
    {"word": "canteen", "translation": "餐厅", "phonetic": "['kæn'ti:n]", "definition": "a place where food is served", "example": "I eat lunch in the canteen."},
    {"word": "office", "translation": "办公室", "phonetic": "['ɒfɪs]", "definition": "a room for working", "example": "My father works in an office."},
    {"word": "floor", "translation": "地面;楼层", "phonetic": "['flɔ:]", "definition": "the bottom surface of a room", "example": "The book is on the floor."},
    {"word": "ground", "translation": "地面", "phonetic": "['graʊnd]", "definition": "the solid surface of the earth", "example": "I sit on the ground."},
    
    # 其他常用词 (Other Common Words)
    {"word": "people", "translation": "人", "phonetic": "['pi:pl]", "definition": "human beings", "example": "There are many people."},
    {"word": "boy", "translation": "男孩", "phonetic": "['bɔɪ]", "definition": "a male child", "example": "He is a boy."},
    {"word": "girl", "translation": "女孩", "phonetic": "['gɜ:l]", "definition": "a female child", "example": "She is a girl."},
    {"word": "man", "translation": "男人", "phonetic": "['mæn]", "definition": "an adult male", "example": "He is a man."},
    {"word": "woman", "translation": "女人", "phonetic": "['wʊmən]", "definition": "an adult female", "example": "She is a woman."},
    {"word": "teacher", "translation": "教师", "phonetic": "['ti:tʃə]", "definition": "a person who teaches", "example": "She is my teacher."},
    {"word": "pupil", "translation": "学生", "phonetic": "['pju:pɪl]", "definition": "a child at school", "example": "I am a pupil."},
    {"word": "thing", "translation": "东西", "phonetic": "['θɪŋ]", "definition": "an object", "example": "What is this thing?"},
    {"word": "idea", "translation": "想法", "phonetic": "['aɪ'dɪə]", "definition": "a thought or suggestion", "example": "I have an idea."},
    {"word": "way", "translation": "方式;道路", "phonetic": "['weɪ]", "definition": "a method or path", "example": "This is the way to school."},
    {"word": "please", "translation": "请", "phonetic": "['pli:z]", "definition": "a polite word", "example": "Please sit down."},
    {"word": "thanks", "translation": "谢谢", "phonetic": "['θæŋks]", "definition": "a word of gratitude", "example": "Thanks for your help."},
    {"word": "sorry", "translation": "对不起", "phonetic": "['sɒri]", "definition": "a word of apology", "example": "Sorry, I am late."},
    {"word": "hello", "translation": "你好", "phonetic": "['hə'ləʊ]", "definition": "a greeting", "example": "Hello, how are you?"},
    {"word": "goodbye", "translation": "再见", "phonetic": "['gʊd'baɪ]", "definition": "a farewell", "example": "Goodbye, see you tomorrow."},
    {"word": "yes", "translation": "是的", "phonetic": "['jes]", "definition": "an affirmative", "example": "Yes, I agree."},
    {"word": "no", "translation": "不", "phonetic": "['nəʊ]", "definition": "a negative", "example": "No, I don't know."},
    {"word": "can", "translation": "能;会", "phonetic": "['kæn]", "definition": "be able to", "example": "I can swim."},
    {"word": "may", "translation": "可以", "phonetic": "['meɪ]", "definition": "be allowed to", "example": "May I come in?"},
    {"word": "some", "translation": "一些", "phonetic": "['sʌm]", "definition": "an unspecified amount", "example": "I have some apples."},
    {"word": "any", "translation": "任何;一些", "phonetic": "['eni]", "definition": "any amount", "example": "Do you have any books?"},
    {"word": "much", "translation": "许多", "phonetic": "['mʌtʃ]", "definition": "a large amount", "example": "I have much homework."},
    {"word": "many", "translation": "许多", "phonetic": "['meni]", "definition": "a large number", "example": "I have many friends."},
    {"word": "lot", "translation": "许多", "phonetic": "['lɒt]", "definition": "a large amount", "example": "I have a lot of books."},
    {"word": "all", "translation": "全部", "phonetic": "['ɔ:l]", "definition": "the whole amount", "example": "I ate all the food."},
    {"word": "both", "translation": "两个都", "phonetic": "['bəʊθ]", "definition": "the two together", "example": "Both of them are students."},
    {"word": "other", "translation": "另外的", "phonetic": "['ʌðə]", "definition": "different from what is mentioned", "example": "Some are here, others are there."},
    {"word": "another", "translation": "另一个", "phonetic": "['ə'nʌðə]", "definition": "one more", "example": "I want another one."},
    {"word": "really", "translation": "真正地", "phonetic": "['rɪəli]", "definition": "in actual fact", "example": "I am really happy."},
    {"word": "very", "translation": "非常", "phonetic": "['veri]", "definition": "to a high degree", "example": "I am very tired."},
    {"word": "too", "translation": "也;太", "phonetic": "['tu:]", "definition": "also or excessively", "example": "I am hungry too."},
    {"word": "also", "translation": "也", "phonetic": "['ɔ:lsəʊ]", "definition": "in addition", "example": "I am also a student."},
    {"word": "just", "translation": "正好;刚才", "phonetic": "['dʒʌst]", "definition": "exactly or recently", "example": "Just do it."},
    {"word": "still", "translation": "仍然", "phonetic": "['stɪl]", "definition": "up to and including the present", "example": "I am still here."},
    {"word": "only", "translation": "只;仅仅", "phonetic": "['əʊnli]", "definition": "and no one or nothing more", "example": "I have only one book."},
    {"word": "even", "translation": "甚至", "phonetic": "['i:vən]", "definition": "used to emphasize something surprising", "example": "Even a child can do this."},
    {"word": "already", "translation": "已经", "phonetic": "['ɔ:l'redi]", "definition": "before or by now", "example": "I have already eaten."},
    {"word": "never", "translation": "从不", "phonetic": "['nevə]", "definition": "at no time", "example": "I never give up."},
    {"word": "always", "translation": "总是", "phonetic": "['ɔ:lweɪz]", "definition": "at all times", "example": "I always get up early."},
    {"word": "usually", "translation": "通常", "phonetic": "['ju:ʒuəli]", "definition": "normally", "example": "I usually walk to school."},
    {"word": "sometimes", "translation": "有时", "phonetic": "['sʌmtaɪmz]", "definition": "occasionally", "example": "I sometimes play games."},
    {"word": "often", "translation": "经常", "phonetic": "['ɒfən]", "definition": "frequently", "example": "I often read books."},
    {"word": "quickly", "translation": "快速地", "phonetic": "['kwɪkli]", "definition": "at a fast speed", "example": "I quickly finished my homework."},
    {"word": "slowly", "translation": "慢速地", "phonetic": "['sləʊli]", "definition": "at a slow speed", "example": "Please speak slowly."},
    {"word": "carefully", "translation": "仔细地", "phonetic": "['keəfəli]", "definition": "with attention", "example": "Listen carefully."},
    {"word": "fast", "translation": "快地", "phonetic": "['fɑ:st]", "definition": "at a quick speed", "example": "Run fast!"},
    {"word": "slow", "translation": "慢的", "phonetic": "['sləʊ]", "definition": "not fast", "example": "The turtle is slow."},
]

def import_words():
    conn = sqlite3.connect('wordmaster.db')
    cursor = conn.cursor()
    
    # 获取第一个词库ID
    cursor.execute('SELECT id FROM dictionaries LIMIT 1')
    result = cursor.fetchone()
    
    if not result:
        print("没有找到词库，请先创建词库。")
        conn.close()
        return
    
    dict_id = result[0]
    
    # 插入单词
    for word in fourth_grade_words:
        cursor.execute('''
            INSERT INTO words (word, translation, phonetic, definition, example, dictionary_id)
            VALUES (?, ?, ?, ?, ?, ?)
        ''', (word['word'], word['translation'], word['phonetic'], 
              word['definition'], word['example'], dict_id))
    
    # 更新词库单词数量
    cursor.execute('UPDATE dictionaries SET word_count = ? WHERE id = ?', 
                   (len(fourth_grade_words), dict_id))
    
    conn.commit()
    print(f"成功导入 {len(fourth_grade_words)} 个单词到词库ID {dict_id}")
    
    conn.close()

if __name__ == '__main__':
    import_words()
